# Generated by Django 2.2.12 on 2021-10-24 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='worker_info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('email', models.EmailField(max_length=254)),
                ('loction', models.CharField(choices=[('full time', 'full time'), ('part time', 'part time')], max_length=10)),
                ('option_time_work', models.IntegerField(default=0)),
                ('time_start_work', models.IntegerField(default=0)),
                ('namber_of_phone', models.IntegerField(default=0)),
                ('disc', models.CharField(max_length=200)),
                ('images', models.ImageField(upload_to='worker_imges')),
                ('abuot_worker', models.CharField(max_length=10)),
                ('published_at', models.DateField(auto_now=True)),
            ],
        ),
    ]
