# Generated by Django 2.2.12 on 2021-10-24 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abuot_team', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worker_info',
            name='loction',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='worker_info',
            name='namber_of_phone',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='worker_info',
            name='option_time_work',
            field=models.CharField(choices=[('full time', 'full time'), ('part time', 'part time')], max_length=10),
        ),
        migrations.AlterField(
            model_name='worker_info',
            name='time_start_work',
            field=models.DateField(default=0),
        ),
    ]
