# Generated by Django 3.0.1 on 2022-03-03 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abuot_team', '0004_auto_20211024_1944'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worker_info',
            name='abuot_worker',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='worker_info',
            name='loction',
            field=models.CharField(max_length=30),
        ),
    ]
