# Generated by Django 3.0.1 on 2022-03-21 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abuot_team', '0005_auto_20220303_2046'),
    ]

    operations = [
        migrations.AddField(
            model_name='worker_info',
            name='Twitter',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='worker_info',
            name='facebook',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
