# Generated by Django 3.0.1 on 2022-03-21 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abuot_team', '0007_worker_info_experience'),
    ]

    operations = [
        migrations.AddField(
            model_name='worker_info',
            name='stars',
            field=models.CharField(max_length=5, null=True),
        ),
    ]
