# Generated by Django 2.2.12 on 2021-10-23 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cars',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=50)),
                ('generation', models.CharField(max_length=50)),
                ('start_of_prodetion', models.IntegerField(default=0)),
                ('contry_prodetion', models.CharField(max_length=50)),
                ('doors', models.IntegerField(default=0)),
                ('colors', models.CharField(max_length=10)),
                ('status', models.CharField(choices=[('New', 'new'), ('used', 'used')], max_length=10)),
                ('price', models.IntegerField(default=0)),
                ('option', models.CharField(choices=[('full option', 'full option'), ('normal', 'normal')], max_length=50)),
                ('namber_of_cylinder', models.IntegerField(default=0)),
                ('power_of_push', models.IntegerField(default=0)),
                ('high_speed', models.IntegerField(default=0)),
                ('disc', models.CharField(max_length=200)),
                ('images', models.ImageField(upload_to='cars_imges')),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
            ],
        ),
    ]
