# Generated by Django 2.2.12 on 2021-10-23 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('browsr_cars', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cars',
            name='published_at',
            field=models.DateField(auto_now=True),
        ),
    ]
