# Generated by Django 2.2.12 on 2021-10-24 00:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('browsr_cars', '0002_cars_published_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='cars',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='browsr_cars.Category'),
        ),
    ]
