# Generated by Django 2.2.12 on 2021-11-07 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('browsr_cars', '0004_auto_20211026_1755'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='images',
            field=models.ImageField(default=1, upload_to='cars_img'),
            preserve_default=False,
        ),
    ]
