# Generated by Django 3.0.1 on 2022-03-03 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('browsr_cars', '0005_category_images'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order_car',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frist_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=50)),
                ('selected_car', models.CharField(max_length=50)),
                ('Email', models.CharField(max_length=50)),
                ('selected', models.CharField(max_length=10)),
                ('checked', models.CharField(choices=[('New', 'new'), ('used', 'used')], max_length=10)),
                ('price', models.IntegerField(default=0)),
                ('option', models.CharField(choices=[('full option', 'full option'), ('normal', 'normal')], max_length=50)),
                ('published_at', models.DateField(auto_now=True)),
            ],
        ),
    ]
