# Generated by Django 3.0.1 on 2022-03-03 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('browsr_cars', '0006_order_car'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order_car',
            name='option',
        ),
        migrations.RemoveField(
            model_name='order_car',
            name='price',
        ),
        migrations.AddField(
            model_name='order_car',
            name='phone',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order_car',
            name='checked',
            field=models.CharField(max_length=10),
        ),
    ]
