# Generated by Django 3.0.1 on 2022-03-03 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('browsr_cars', '0007_auto_20220303_2054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order_car',
            name='Email',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='order_car',
            name='checked',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='order_car',
            name='frist_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='order_car',
            name='last_name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='order_car',
            name='phone',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='order_car',
            name='published_at',
            field=models.DateField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='order_car',
            name='selected',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='order_car',
            name='selected_car',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
