# Generated by Django 3.0.1 on 2022-03-22 21:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('browsr_cars', '0008_auto_20220303_2131'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order_car',
            name='selected_car',
        ),
    ]
